import AdminHeader from "@/components/shared/AdminHeader";
import SubHeader from "@/components/shared/SubHeader";
import AuthProvider from "../providers/AuthProvider";






export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (

      <div
        className={'bg-white dark:bg-white'}
      >

<AuthProvider>
     <AdminHeader/>
 
        <div className="mt-16 ">
          {children}
        </div>
</AuthProvider>
      </div>

  );
}
